import ROOT
ROOT.gROOT.SetBatch(1)
ROOT.gStyle.SetOptStat(0)
import sys

boson=sys.argv[1]
file_LO=ROOT.TFile.Open(sys.argv[2])
file_NLO=ROOT.TFile.Open(sys.argv[3])

canvas=ROOT.TCanvas("canvas", "canvas", 4000, 3000)
canvas_3D=ROOT.TCanvas("canvas_3D", "canvas_3D", 4500, 1700)

legend=ROOT.TLegend(0.15,0.15)
legend2=ROOT.TLegend(0.15,0.15)
######################################################

hist=file_LO.Get(boson+"_boson_pt")
hist2=file_NLO.Get(boson+"_boson_pt")
hist4=file_LO.Get(boson + "_boson_pt_to1TeV")
hist5=file_NLO.Get(boson +"_boson_pt_to1TeV")
hist7=file_LO.Get(boson + "_boson_eta")
hist8=file_NLO.Get(boson + "_boson_eta")
hist10=file_LO.Get(boson + "_boson_phi")
hist11=file_NLO.Get(boson + "_boson_phi")
hist13=file_LO.Get(boson + "_jets_fuehrende_Ordnung_pt")
hist14=file_NLO.Get(boson + "_jets_fuehrende_Ordnung_pt")
hist16=file_LO.Get(boson + "_jets_fuehrende_Ordnung_eta")
hist17=file_NLO.Get(boson + "_jets_fuehrende_Ordnung_eta")
hist19=file_LO.Get(boson + "_jets_anzahl")
hist20=file_NLO.Get(boson + "_jets_anzahl")
hist22=file_LO.Get(boson + "_jets_HT")
hist23=file_NLO.Get(boson + "_jets_HT")
hist25=file_LO.Get(boson + "_boson_jets_fuehrende_Ordnung_DeltaPhi")
hist26=file_NLO.Get(boson + "_boson_jets_fuehrende_Ordnung_DeltaPhi")
hist28=file_LO.Get(boson + "_boson_transverse_mass")
hist29=file_NLO.Get(boson + "_boson_transverse_mass")
hist1_2D=file_LO.Get(boson + "_boson_jets_fuehrende_Ordnung_pt_2D")
hist2_2D=file_NLO.Get(boson + "_boson_jets_fuehrende_Ordnung_pt_2D")
hist4_2D=file_LO.Get(boson + "_boson_pt_DeltaPhi_2D")
hist5_2D=file_NLO.Get(boson + "_boson_pt_DeltaPhi_2D")
hist7_2D=file_LO.Get(boson + "_jets_fuehrende_Ordnung_pt_DeltaPhi_2D")
hist8_2D=file_NLO.Get(boson + "_jets_fuehrende_Ordnung_pt_DeltaPhi_2D")
hist10_2D=file_LO.Get(boson + "_jets_anzahl_HT_2D")
hist11_2D=file_NLO.Get(boson + "_jets_anzahl_HT_2D")
hist13_2D=file_LO.Get(boson + "_boson_transverse_mass_pt_2D")
hist14_2D=file_NLO.Get(boson + "_boson_transverse_mass_pt_2D")
hist16_2D=file_LO.Get(boson + "_boson_transverse_mass_phizwlundnu_2D")
hist17_2D=file_NLO.Get(boson + "_boson_transverse_mass_phizwlundnu_2D")
hist1_3D=file_LO.Get(boson + "_boson_pt_jets_fuehrende_Ordnung_pt_DeltaPhi_3D")
hist2_3D=file_NLO.Get(boson + "_boson_pt_jets_fuehrende_Ordnung_pt_DeltaPhi_3D")
hist4_3D=file_LO.Get(boson+ "_boson_pt_jets_fuehrende_Ordnung_pt_anzahl_3D")
hist5_3D=file_NLO.Get(boson+ "_boson_pt_jets_fuehrende_Ordnung_pt_anzahl_3D")
hist7_3D=file_LO.Get(boson + "_boson_pt_DeltaPhi_anzahl_3D")
hist8_3D=file_NLO.Get(boson + "_boson_pt_DeltaPhi_anzahl_3D")

##################################################

hist3=hist2.Clone()
hist3.Divide(hist)
hist.GetXaxis().SetTitle("transversaler Impuls in GeV")
hist.GetYaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist.GetXaxis().SetRangeUser(30.0,1000.0)
#hist.GetYaxis().SetRangeUser(0.00000001,100000000)
hist.GetXaxis().CenterTitle()
hist.GetYaxis().CenterTitle()
hist.SetLineColor(1)
hist2.SetLineColor(2)
hist3.GetXaxis().SetTitle("transversaler Impuls in GeV")
hist3.GetYaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist3.GetXaxis().SetRangeUser(30.0,1000.0)
hist3.GetXaxis().CenterTitle()
hist3.GetYaxis().CenterTitle()
hist3.GetYaxis().SetRangeUser(0,2)
hist.SetTitle("Transversalimpuls des "+ boson+ " Bosons")
hist3.SetTitle("")

hist6=hist5.Clone()
hist6.Divide(hist4)
hist4.GetXaxis().SetTitle("transversaler Impuls in GeV")
hist4.GetYaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")    
hist4.GetXaxis().CenterTitle()
hist4.GetYaxis().CenterTitle()
#hist.GetYaxis().SetRangeUser(0.0000001,100)
hist4.SetLineColor(1)
hist5.SetLineColor(2)
hist6.GetXaxis().SetTitle("transversaler Impuls in GeV")
hist6.GetYaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist6.GetXaxis().CenterTitle()
hist6.GetYaxis().CenterTitle() 
hist6.GetYaxis().SetRangeUser(0,2)
hist4.SetTitle("Transversalimpuls des "+ boson+ " Bosons")
hist6.SetTitle("")

hist9=hist8.Clone()
hist9.Divide(hist7)
hist7.GetXaxis().SetTitle("Pseudorapiditaet")
hist7.GetYaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")    
hist7.GetXaxis().CenterTitle()
hist7.GetYaxis().CenterTitle()
hist7.SetLineColor(1)
hist8.SetLineColor(2)
hist7.GetYaxis().SetRangeUser(0,3000)
#hist7.GetXaxis().SetRangeUser(-20,20)
hist9.GetXaxis().SetTitle("Pseudorapiditaet")
hist9.GetYaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist9.GetXaxis().CenterTitle()
hist9.GetYaxis().CenterTitle()
hist9.GetYaxis().SetRangeUser(0,2)
hist7.SetTitle("Pseudorapiditaet des "+ boson+ " Bosons")
hist9.SetTitle("")

hist12=hist11.Clone()
hist12.Divide(hist10)
hist10.GetXaxis().SetTitle("Azimutalwinkel")
hist10.GetYaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")    
hist10.GetXaxis().CenterTitle()
hist10.GetYaxis().CenterTitle()
hist10.SetLineColor(1)
hist11.SetLineColor(2)
hist10.GetYaxis().SetRangeUser(950,1350.0)
hist12.GetXaxis().SetTitle("Azimutalwinkel")
hist12.GetYaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist12.GetXaxis().CenterTitle()
hist12.GetYaxis().CenterTitle()
hist12.GetYaxis().SetRangeUser(0,2)
hist10.SetTitle("Azimutalwinkel des "+ boson+ " Bosons")
hist12.SetTitle("")

hist15=hist14.Clone()
hist15.Divide(hist13)
hist13.GetXaxis().SetTitle("transversaler Impuls in GeV")
hist13.GetYaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist13.GetXaxis().CenterTitle()
hist13.GetYaxis().CenterTitle()
hist13.SetLineColor(1)
hist14.SetLineColor(2)
hist15.GetXaxis().SetTitle("transversaler Impuls in GeV")
hist15.GetYaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist15.GetXaxis().CenterTitle()
hist15.GetYaxis().CenterTitle()
hist15.GetYaxis().SetRangeUser(0,2)
hist13.SetTitle("Transversalimpuls des fuehrenden Jets")
hist15.SetTitle("")

hist18=hist17.Clone()
hist18.Divide(hist16)
hist16.GetXaxis().SetTitle("Pseudorapiditaet")
hist16.GetYaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")    
hist16.GetXaxis().CenterTitle()
hist16.GetYaxis().CenterTitle()
hist16.SetLineColor(1)
hist17.SetLineColor(2)
hist16.GetYaxis().SetRangeUser(0,4000)
hist16.GetXaxis().SetRangeUser(-8,8)
hist18.GetXaxis().SetTitle("Pseudorapiditaet")
hist18.GetYaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist18.GetXaxis().CenterTitle()
hist18.GetYaxis().CenterTitle()
hist18.GetXaxis().SetRangeUser(-8,8)
hist18.GetYaxis().SetRangeUser(0,2)
hist16.SetTitle("Pseudorapiditaet des fuehrenden Jets")
hist18.SetTitle("")

hist21=hist20.Clone()
hist21.Divide(hist19)
hist19.GetXaxis().SetTitle("Anzahl der Jets")
hist19.GetYaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")    
hist19.GetXaxis().CenterTitle()
hist19.GetYaxis().CenterTitle()
hist19.SetLineColor(1)
hist20.SetLineColor(2)
hist19.GetXaxis().SetRangeUser(0,14)
hist21.GetXaxis().SetRangeUser(0,14)
hist21.GetXaxis().SetTitle("Anzahl der Jets")
hist21.GetYaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist21.GetXaxis().CenterTitle()
hist21.GetYaxis().CenterTitle()
hist21.GetYaxis().SetRangeUser(0,2)
hist19.SetTitle("Anzahl der Jets mit pt>=30 GeV,|eta|<=2.4")
hist21.SetTitle("")

hist24=hist23.Clone()
hist24.Divide(hist22)
hist22.GetXaxis().SetTitle("Summe der Transversalimpulse aller Jets in GeV")
hist22.GetYaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist22.GetXaxis().CenterTitle()
hist22.GetYaxis().CenterTitle()
hist22.SetLineColor(1)
hist23.SetLineColor(2)
hist24.GetXaxis().SetTitle("Summe der Transversalimpulse aller Jets in GeV")
hist24.GetYaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist24.GetXaxis().CenterTitle()
hist24.GetYaxis().CenterTitle()
hist24.GetYaxis().SetRangeUser(0,2)
hist22.SetTitle("Summe der Transversalimpulse aller Jets mit pt>=30 GeV,|eta|<=2.4")
hist24.SetTitle("")

hist27=hist26.Clone()
hist27.Divide(hist25)
hist25.GetXaxis().SetTitle("Betrag des Azimutalwinkels zwischen "+boson+" Boson und fuehrendem Jet")
hist25.GetYaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist25.GetXaxis().CenterTitle()
hist25.GetYaxis().CenterTitle()
hist25.SetLineColor(1)
hist26.SetLineColor(2)
hist27.GetXaxis().SetTitle("Betrag des Azimutalwinkels zwischen "+boson+" Boson und fuehrendem Jet")
hist27.GetYaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist27.GetXaxis().CenterTitle()
hist27.GetYaxis().CenterTitle()
hist27.GetYaxis().SetRangeUser(0,2)
hist25.SetTitle("Betrag des Azimutalwinkels zwischen "+boson+ " Boson und fuehrendem Jet")
hist27.SetTitle("")

hist30=hist29.Clone()
hist30.Divide(hist28)
hist28.GetXaxis().SetTitle("transversale Masse des W Bosons in GeV")
hist28.GetYaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
#hist28.GetXaxis().SetRangeUser(30.0,1000.0)
#hist.GetYaxis().SetRangeUser(0.00000001,100000000)
hist28.GetXaxis().CenterTitle()
hist28.GetYaxis().CenterTitle()
hist28.SetLineColor(1)
hist29.SetLineColor(2)
hist30.GetXaxis().SetTitle("transversale Masse des W Bosons in GeV")
hist30.GetYaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
#hist30.GetXaxis().SetRangeUser(30.0,1000.0)
hist30.GetXaxis().CenterTitle()
hist30.GetYaxis().CenterTitle()
hist30.GetYaxis().SetRangeUser(0,2)
hist28.SetTitle("Transversale Masse des W Bosons")
hist30.SetTitle("")


hist3_2D=hist2_2D.Clone()
hist3_2D.Divide(hist1_2D)
hist1_2D.GetXaxis().SetTitle("transversaler Impuls des "+boson+" Bosons in GeV")
hist1_2D.GetYaxis().SetTitle("transversaler Impuls des fuehrenden Jets in GeV")
hist1_2D.GetZaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist1_2D.GetXaxis().CenterTitle()
hist1_2D.GetYaxis().CenterTitle()
hist1_2D.GetZaxis().CenterTitle()
hist2_2D.GetXaxis().SetTitle("transversaler Impuls des "+boson+" Bosons in GeV")
hist2_2D.GetYaxis().SetTitle("transversaler Impuls des fuehrenden Jets in GeV")
hist2_2D.GetZaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist2_2D.GetXaxis().CenterTitle()
hist2_2D.GetYaxis().CenterTitle()
hist2_2D.GetZaxis().CenterTitle()
hist3_2D.GetXaxis().SetTitle("transversaler Impuls des "+boson+" Bosons in GeV")
hist3_2D.GetYaxis().SetTitle("transversaler Impuls des fuehrenden Jets in GeV")
hist3_2D.GetZaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist3_2D.GetXaxis().CenterTitle()
hist3_2D.GetYaxis().CenterTitle()
hist3_2D.GetZaxis().CenterTitle()
hist3_2D.GetZaxis().SetRangeUser(0,2)
hist1_2D.SetTitle("LO")
hist2_2D.SetTitle("NLO")
hist3_2D.SetTitle("Verhaeltnis NLO zu LO")

hist6_2D=hist5_2D.Clone()
hist6_2D.Divide(hist4_2D)
hist4_2D.GetXaxis().SetTitle("transversaler Impuls des "+boson+" Bosons in GeV")
hist4_2D.GetYaxis().SetTitle("Azimutalwinkel zwischen "+boson+" Boson und fuehrendem Jet") 
hist4_2D.GetZaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist4_2D.GetXaxis().CenterTitle()
hist4_2D.GetYaxis().CenterTitle()
hist4_2D.GetZaxis().CenterTitle()
hist5_2D.GetXaxis().SetTitle("transversaler Impuls des "+boson+" Bosons in GeV")
hist5_2D.GetYaxis().SetTitle("Azimutalwinkel zwischen "+boson+" Boson und fuehrendem Jet")    
hist5_2D.GetZaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist5_2D.GetXaxis().CenterTitle()
hist5_2D.GetYaxis().CenterTitle()
hist5_2D.GetZaxis().CenterTitle()
hist6_2D.GetXaxis().SetTitle("transversaler Impuls des "+boson+" Bosons in GeV")
hist6_2D.GetYaxis().SetTitle("Azimutalwinkel zwischen "+boson+" Boson und fuehrendem Jet") 
hist6_2D.GetZaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist6_2D.GetXaxis().CenterTitle()
hist6_2D.GetYaxis().CenterTitle() 
hist6_2D.GetZaxis().CenterTitle()
hist6_2D.GetZaxis().SetRangeUser(0,2)
hist4_2D.SetTitle("LO")
hist5_2D.SetTitle("NLO")
hist6_2D.SetTitle("Verhaeltnis NLO zu LO")

hist9_2D=hist8_2D.Clone()
hist9_2D.Divide(hist7_2D)
hist7_2D.GetXaxis().SetTitle("transversaler Impuls des fuehrenden Jets in GeV")
hist7_2D.GetYaxis().SetTitle("Azimutalwinkel zwischen "+boson+" Boson und fuehrendem Jet")  
hist7_2D.GetZaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist7_2D.GetXaxis().CenterTitle()
hist7_2D.GetYaxis().CenterTitle()
hist7_2D.GetZaxis().CenterTitle()
hist8_2D.GetXaxis().SetTitle("transversaler Impuls des fuehrenden Jets in GeV")
hist8_2D.GetYaxis().SetTitle("Azimutalwinkel zwischen "+boson+" Boson und fuehrendem Jet")   
hist8_2D.GetZaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist8_2D.GetXaxis().CenterTitle()
hist8_2D.GetYaxis().CenterTitle()
hist8_2D.GetZaxis().CenterTitle()
hist9_2D.GetXaxis().SetTitle("transversaler Impuls des fuehrenden Jets in GeV")
hist9_2D.GetYaxis().SetTitle("Azimutalwinkel zwischen "+boson+" Boson und fuehrendem Jet")
hist9_2D.GetZaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist9_2D.GetXaxis().CenterTitle()
hist9_2D.GetYaxis().CenterTitle()
hist9_2D.GetZaxis().CenterTitle()
hist9_2D.GetZaxis().SetRangeUser(0,2)
hist7_2D.SetTitle("LO")
hist8_2D.SetTitle("NLO")
hist9_2D.SetTitle("Verhaeltnis NLO zu LO")

hist12_2D=hist11_2D.Clone()
hist12_2D.Divide(hist10_2D)
hist10_2D.GetXaxis().SetTitle("Anzahl der Jets mit pt>=30 GeV,|eta|<=2.4")
hist10_2D.GetYaxis().SetTitle("Summe der pt aller Jets in GeV mit pt>=30 GeV,|eta|<=2.4")  
hist10_2D.GetZaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist10_2D.GetXaxis().CenterTitle()
hist10_2D.GetYaxis().CenterTitle()
hist10_2D.GetZaxis().CenterTitle()
hist10_2D.GetXaxis().SetRangeUser(1,12)
hist11_2D.GetXaxis().SetTitle("Anzahl der Jets mit pt>=30 GeV,|eta|<=2.4")
hist11_2D.GetYaxis().SetTitle("Summe der pt aller Jets in GeV mit pt>=30 GeV,|eta|<=2.4")
hist11_2D.GetZaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist11_2D.GetXaxis().CenterTitle()
hist11_2D.GetYaxis().CenterTitle()
hist11_2D.GetZaxis().CenterTitle()
hist11_2D.GetXaxis().SetRangeUser(1,12)
hist12_2D.GetXaxis().SetTitle("Anzahl der Jets mit pt>=30 GeV,|eta|<=2.4")
hist12_2D.GetYaxis().SetTitle("Summe der pt aller Jets in GeV mit pt>=30 GeV,|eta|<=2.4")
hist12_2D.GetZaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist12_2D.GetXaxis().CenterTitle()
hist12_2D.GetYaxis().CenterTitle()
hist12_2D.GetZaxis().CenterTitle()
hist12_2D.GetXaxis().SetRangeUser(1,12)
hist12_2D.GetZaxis().SetRangeUser(0,2)
hist10_2D.SetTitle("LO")
hist11_2D.SetTitle("NLO")
hist12_2D.SetTitle("Verhaeltnis NLO zu LO")

hist15_2D=hist14_2D.Clone()
hist15_2D.Divide(hist13_2D)
hist13_2D.GetXaxis().SetTitle("transversale Masse des W Bosons in GeV")
hist13_2D.GetYaxis().SetTitle("transversaler Impuls des W Bosons in GeV")
hist13_2D.GetZaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist13_2D.GetXaxis().CenterTitle()
hist13_2D.GetYaxis().CenterTitle()
hist13_2D.GetZaxis().CenterTitle()
hist14_2D.GetXaxis().SetTitle("transversale Masse des W Bosons in GeV")
hist14_2D.GetYaxis().SetTitle("transversaler Impuls des W Bosons in GeV")
hist14_2D.GetZaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist14_2D.GetXaxis().CenterTitle()
hist14_2D.GetYaxis().CenterTitle()
hist14_2D.GetZaxis().CenterTitle()
hist15_2D.GetXaxis().SetTitle("transversale Masse des W Bosons in GeV")
hist15_2D.GetYaxis().SetTitle("transversaler Impuls des W Bosons in GeV")
hist15_2D.GetZaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist15_2D.GetXaxis().CenterTitle()
hist15_2D.GetYaxis().CenterTitle()
hist15_2D.GetZaxis().CenterTitle()
hist15_2D.GetZaxis().SetRangeUser(0,2)
hist13_2D.SetTitle("LO")
hist14_2D.SetTitle("NLO")
hist15_2D.SetTitle("Verhaeltnis NLO zu LO")

hist18_2D=hist17_2D.Clone()
hist18_2D.Divide(hist16_2D)
hist16_2D.GetXaxis().SetTitle("transversale Masse des W Bosons in GeV")
hist16_2D.GetYaxis().SetTitle("Azimutalwinkel zwischen geladenem Lepton und Neutrino")    
hist16_2D.GetZaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist16_2D.GetXaxis().CenterTitle()
hist16_2D.GetYaxis().CenterTitle()
hist16_2D.GetZaxis().CenterTitle()
hist17_2D.GetXaxis().SetTitle("transversale Masse des W Bosons in GeV")
hist17_2D.GetYaxis().SetTitle("Azimutalwinkel zwischen geladenem Lepton und Neutrino")
hist17_2D.GetZaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist17_2D.GetXaxis().CenterTitle()
hist17_2D.GetYaxis().CenterTitle()
hist17_2D.GetZaxis().CenterTitle()
hist18_2D.GetXaxis().SetTitle("transversale Masse des W Bosons in GeV")
hist18_2D.GetYaxis().SetTitle("Azimutalwinkel zwischen geladenem Lepton und Neutrino")
hist18_2D.GetZaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist18_2D.GetXaxis().CenterTitle()
hist18_2D.GetYaxis().CenterTitle()
hist18_2D.GetZaxis().CenterTitle()
hist18_2D.GetZaxis().SetRangeUser(0,2)
hist16_2D.SetTitle("LO")
hist17_2D.SetTitle("NLO")
hist18_2D.SetTitle("Verhaeltnis NLO zu LO")

hist3_3D=hist2_3D.Clone()
hist3_3D.Divide(hist1_3D)
hist1_3D.GetXaxis().SetTitle("transversaler Impuls des "+boson+" Bosons in GeV")
hist1_3D.GetYaxis().SetTitle("transversaler Impuls des fuehrenden Jets in GeV ")
hist1_3D.GetZaxis().SetTitle("Azimutalwinkel zwischen "+boson+" Boson und fuehrendem Jet")
hist1_3D.GetXaxis().CenterTitle()
hist1_3D.GetYaxis().CenterTitle()
hist1_3D.GetZaxis().CenterTitle()
hist2_3D.GetXaxis().SetTitle("transversaler Impuls des "+boson+" Bosons in GeV")
hist2_3D.GetYaxis().SetTitle("transversaler Impuls in GeV vom fuehrenden Jet")
hist2_3D.GetZaxis().SetTitle("Azimutalwinkel zwischen "+boson+" Boson und fuehrendem Jet")
hist2_3D.GetXaxis().CenterTitle()
hist2_3D.GetYaxis().CenterTitle()
hist2_3D.GetZaxis().CenterTitle()
hist3_3D.GetXaxis().SetTitle("transversaler Impuls des "+boson+" Bosons in GeV")
hist1_3D.GetYaxis().SetTitle("transversaler Impuls des fuehrenden Jets in GeV ")
hist3_3D.GetZaxis().SetTitle("Verhaeltnis NLO/LO")
hist3_3D.GetXaxis().CenterTitle()
hist3_3D.GetYaxis().CenterTitle()
hist3_3D.GetZaxis().CenterTitle()
hist1_3D.SetTitle("LO")
hist2_3D.SetTitle("NLO")
hist3_3D.SetTitle("Verhaeltnis NLO zu LO")

hist6_3D=hist5_3D.Clone()
hist6_3D.Divide(hist4_3D)
hist4_3D.GetXaxis().SetTitle("transversaler Impuls des "+boson+" Bosons in GeV")
hist4_3D.GetYaxis().SetTitle("transversaler Impuls des fuehrenden Jets in GeV")
hist4_3D.GetZaxis().SetTitle("Anzahl der Jets mit pt>=30 GeV,|eta|<=2.4") 
hist4_3D.GetZaxis().SetRangeUser(0,14)
hist5_3D.GetZaxis().SetRangeUser(0,14)
hist6_3D.GetZaxis().SetRangeUser(0,14)
hist4_3D.GetXaxis().CenterTitle()
hist4_3D.GetYaxis().CenterTitle()
hist4_3D.GetZaxis().CenterTitle()
hist5_3D.GetXaxis().SetTitle("transversaler Impuls des "+boson+" Bosons in GeV")
hist5_3D.GetYaxis().SetTitle("transversaler Impuls des fuehrenden Jets in GeV")
hist5_3D.GetZaxis().SetTitle("Anzahl der Jets mit pt>=30 GeV,|eta|<=2.4")    
hist5_3D.GetXaxis().CenterTitle()
hist5_3D.GetYaxis().CenterTitle()
hist5_3D.GetZaxis().CenterTitle()
hist6_3D.GetXaxis().SetTitle("transversaler Impuls des "+boson+" Bosons in GeV")
hist6_3D.GetYaxis().SetTitle("transversaler Impuls des fuehrenden Jets in GeV")
hist6_3D.GetZaxis().SetTitle("Verhaeltnis NLO/LO")
hist6_3D.GetXaxis().CenterTitle()
hist6_3D.GetYaxis().CenterTitle()
hist6_3D.GetZaxis().CenterTitle()
hist4_3D.SetTitle("LO")
hist5_3D.SetTitle("NLO")
hist6_3D.SetTitle("Verhaeltnis NLO zu LO")

hist9_3D=hist8_3D.Clone()
hist9_3D.Divide(hist7_3D)
hist7_3D.GetXaxis().SetTitle("transversaler Impuls des "+boson+" Bosons in GeV")
hist7_3D.GetYaxis().SetTitle("Azimutalwinkel zwischen "+boson+" Boson und fuehrendem Jet")
hist7_3D.GetZaxis().SetTitle("Anzahl der Jets mit pt>=30 GeV,|eta|<=2.4")
hist7_3D.GetXaxis().CenterTitle()
hist7_3D.GetYaxis().CenterTitle()
hist7_3D.GetZaxis().CenterTitle()
hist7_3D.GetZaxis().SetRangeUser(0,14)
hist8_3D.GetZaxis().SetRangeUser(0,14)
hist9_3D.GetZaxis().SetRangeUser(0,14)
hist8_3D.GetXaxis().SetTitle("transversaler Impuls des "+boson+" Bosons in GeV")
hist8_3D.GetYaxis().SetTitle("Azimutalwinkel zwischen "+boson+" Boson und fuehrendem Jet")
hist8_3D.GetZaxis().SetTitle("Anzahl der Jets mit pt>=30 GeV,|eta|<=2.4")
hist8_3D.GetXaxis().CenterTitle()
hist8_3D.GetYaxis().CenterTitle()
hist8_3D.GetZaxis().CenterTitle()
hist9_3D.GetXaxis().SetTitle("transversaler Impuls in GeV vom fuehrendem Jet")
hist9_3D.GetYaxis().SetTitle("Azimutalwinkel zwischen "+boson+" Boson und fuehrendem Jet")
hist9_3D.GetZaxis().SetTitle("Verhaeltnis NLO/LO")
hist9_3D.GetXaxis().CenterTitle()
hist9_3D.GetYaxis().CenterTitle()
hist9_3D.GetZaxis().CenterTitle()
hist7_3D.SetTitle("LO")
hist8_3D.SetTitle("NLO")
hist9_3D.SetTitle("Verhaeltnis NLO zu LO")
########################################
legend.AddEntry(hist, "LO", "l")
legend.AddEntry(hist2, "NLO", "l")

canvas.Divide(1,2)
canvas.cd(1).SetLogy(1)
canvas.cd(1)
hist.Draw("histe")
hist2.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist3.Draw("histe")

canvas.Print(boson + "_boson_pt.png")
#canvas.Print(boson + "_boson_pt.pdf")
canvas.Clear()
legend.Clear()
#########################################
legend.AddEntry(hist4, "LO", "l")
legend.AddEntry(hist5, "NLO", "l")

canvas.Divide(1,2)
canvas.cd(1).SetLogy(1)
canvas.cd(1)
hist4.Draw("histe")
hist5.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist6.Draw("histe")

canvas.Print(boson + "_boson_pt_to1TeV.png")
#canvas.Print(boson + "_boson_pt_to1TeV.pdf")
canvas.Clear()
legend.Clear()
###########################################
legend.AddEntry(hist7, "LO", "l")
legend.AddEntry(hist8, "NLO", "l")

canvas.Divide(1,2)
canvas.cd(1)
hist7.Draw("histe")
hist8.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist9.Draw("histe")

canvas.Print(boson + "_boson_eta.png")
#canvas.Print(boson + "_boson_eta.pdf")
canvas.Clear()
legend.Clear()
################################################
legend.AddEntry(hist10, "LO", "l")
legend.AddEntry(hist11, "NLO", "l")

canvas.Divide(1,2)
canvas.cd(1)
hist10.Draw("histe")
hist11.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist12.Draw("histe")

canvas.Print(boson + "_boson_phi.png")
#canvas.Print(boson + "_boson_phi.pdf")
canvas.Clear()
legend.Clear()
###########################################
legend.AddEntry(hist13, "LO", "l")
legend.AddEntry(hist14, "NLO", "l")

canvas.Divide(1,2)
canvas.cd(1).SetLogy(1)
canvas.cd(1)
hist13.Draw("histe")
hist14.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist15.Draw("histe")

canvas.Print(boson + "_jets_fuehrende_Ordnung_pt.png")
#canvas.Print(boson + "_jets_fuehrende_Ordnung_pt.pdf")
canvas.Clear()
legend.Clear()
############################################
legend.AddEntry(hist16, "LO", "l")
legend.AddEntry(hist17, "NLO", "l")

canvas.Divide(1,2)
canvas.cd(1)
hist16.Draw("histe")
hist17.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist18.Draw("histe")

canvas.Print(boson + "_jets_fuehrende_Ordnung_eta.png")
#canvas.Print(boson + "_jets_fuehrende_Ordnung_eta.pdf")
canvas.Clear()
legend.Clear()
############################################
legend.AddEntry(hist19, "LO", "l")
legend.AddEntry(hist20, "NLO", "l")

canvas.Divide(1,2)
canvas.cd(1)
canvas.cd(1).SetLogy(1)
hist19.Draw("histe")
hist20.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist21.Draw("histe")

canvas.Print(boson + "_jets_anzahl.png")
#canvas.Print(boson + "_jets_anzahl.pdf")
canvas.Clear()
legend.Clear()
##############################################
legend.AddEntry(hist22, "LO", "l")
legend.AddEntry(hist23, "NLO", "l")

canvas.Divide(1,2)
canvas.cd(1).SetLogy(1)
canvas.cd(1)
hist22.Draw("histe")
hist23.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist24.Draw("histe")

canvas.Print(boson + "_jets_HT.png")
#canvas.Print(boson + "_jets_HT.pdf")
canvas.Clear()
legend.Clear()
###########################################
legend.AddEntry(hist25, "LO", "l")
legend.AddEntry(hist26, "NLO", "l")

canvas.Divide(1,2)
#canvas.cd(1).SetLogy(1)
canvas.cd(1)
hist25.Draw("histe")
hist26.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist27.Draw("histe")

canvas.Print(boson + "_boson_jets_fuehrende_Ordnung_DeltaPhi.png")
#canvas.Print(boson + "_boson_jets_fuehrende_Ordnung_DeltaPhi.pdf")
canvas.Clear()
legend.Clear()
###########################################
legend.AddEntry(hist28, "LO", "l")
legend.AddEntry(hist29, "NLO", "l")

canvas.Divide(1,2)
canvas.cd(1).SetLogy(1)
canvas.cd(1)
hist28.Draw("histe")
hist29.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist30.Draw("histe")

canvas.Print(boson + "_boson_transverse_mass.png")
#canvas.Print(boson + "_boson_transverse_mass.pdf")
canvas.Clear()
legend.Clear()
##########################################
legend.AddEntry(hist1_2D, "LO", "f")
legend.AddEntry(hist2_2D, "NLO", "f")

canvas.Divide(1,3)
canvas.cd(1).SetLogz(1)
canvas.cd(1)
ROOT.gPad.SetRightMargin(0.2)
hist1_2D.Draw("colz")
canvas.cd(2)
ROOT.gPad.SetRightMargin(0.2)
hist2_2D.Draw("colz")
canvas.cd(2).SetLogz(1)
canvas.cd(3)
ROOT.gPad.SetRightMargin(0.2)
hist3_2D.Draw("colz")

canvas.Print(boson + "_boson_jets_fuehrende_Ordnung_pt_2D.png")
#canvas.Print(boson + "_boson_jets_fuehrende_Ordnung_pt_2D.pdf")
canvas.Clear()
legend.Clear()
###############################################
legend.AddEntry(hist4_2D, "LO", "f")
legend.AddEntry(hist5_2D, "NLO", "f")

canvas.Divide(1,3)
canvas.cd(1).SetLogz(1)
canvas.cd(1)
ROOT.gPad.SetRightMargin(0.2)
hist4_2D.Draw("colz")
canvas.cd(2)
ROOT.gPad.SetRightMargin(0.2)
hist5_2D.Draw("colz")
canvas.cd(2).SetLogz(1)
canvas.cd(3)
ROOT.gPad.SetRightMargin(0.2)
hist6_2D.Draw("colz")

canvas.Print(boson + "_boson_pt_DeltaPhi_2D.png")
#canvas.Print(boson + "_boson_pt_DeltaPhi_2D.pdf")
canvas.Clear()
legend.Clear()
############################################
legend.AddEntry(hist7_2D, "LO", "f")
legend.AddEntry(hist8_2D, "NLO", "f")

canvas.Divide(1,3)
canvas.cd(1).SetLogz(1)
canvas.cd(1)
ROOT.gPad.SetRightMargin(0.2)
hist7_2D.Draw("colz")
canvas.cd(2)
ROOT.gPad.SetRightMargin(0.2)
hist8_2D.Draw("colz")
canvas.cd(2).SetLogz(1)
canvas.cd(3)
ROOT.gPad.SetRightMargin(0.2)
hist9_2D.Draw("colz")

canvas.Print(boson + "_jets_fuehrende_Ordnung_pt_DeltaPhi_2D.png")
#canvas.Print(boson + "_jets_fuehrende_Ordnung_pt_DeltaPhi_2D.pdf")
canvas.Clear()
legend.Clear()
############################################
legend.AddEntry(hist10_2D, "LO", "f")
legend.AddEntry(hist11_2D, "NLO", "f")

canvas.Divide(1,3)
canvas.cd(1).SetLogz(1)
canvas.cd(1)
ROOT.gPad.SetRightMargin(0.2)
hist10_2D.Draw("colz")
canvas.cd(2)
ROOT.gPad.SetRightMargin(0.2)
hist11_2D.Draw("colz")
canvas.cd(2).SetLogz(1)
canvas.cd(3)
ROOT.gPad.SetRightMargin(0.2)
hist12_2D.Draw("colz")

canvas.Print(boson + "_jets_anzahl_HT_2D.png")
#canvas.Print(boson + "_jets_anzahl_HT_2D.pdf")
canvas.Clear()
legend.Clear()
##########################################
legend.AddEntry(hist13_2D, "LO", "f")
legend.AddEntry(hist14_2D, "NLO", "f")

canvas.Divide(1,3)
canvas.cd(1).SetLogz(1)
canvas.cd(1)
ROOT.gPad.SetRightMargin(0.2)
hist13_2D.Draw("colz")
canvas.cd(2)
ROOT.gPad.SetRightMargin(0.2)
hist14_2D.Draw("colz")
canvas.cd(2).SetLogz(1)
canvas.cd(3)
ROOT.gPad.SetRightMargin(0.2)
hist15_2D.Draw("colz")

canvas.Print(boson + "_boson_transverse_mass_pt_2D.png")
#canvas.Print(boson + "_boson_transverse_mass_pt_2D.pdf")
canvas.Clear()
legend.Clear()
###########################################
legend.AddEntry(hist16_2D, "LO", "l")
legend.AddEntry(hist17_2D, "NLO", "l")

canvas.Divide(1,3)
canvas.cd(1).SetLogz(1)
canvas.cd(1)
ROOT.gPad.SetRightMargin(0.2)
hist16_2D.Draw("colz")
canvas.cd(2)
ROOT.gPad.SetRightMargin(0.2)
hist17_2D.Draw("colz")
canvas.cd(2).SetLogz(1)
canvas.cd(3)
ROOT.gPad.SetRightMargin(0.2)
hist18_2D.Draw("colz")

canvas.Print(boson + "_boson_transverse_mass_phizwlundnu_2D.png")
#canvas.Print(boson + "_boson_transverse_mass_phizwlundnu_2D.pdf")
canvas.Clear()
legend.Clear()
###########################################
legend.AddEntry(hist1_3D, "LO", "f")
legend.AddEntry(hist2_3D, "NLO", "f")

canvas_3D.Divide(2,2)
#canvas.cd(1).SetLogy(1)
#canvas.cd(1).SetLogx(1)
canvas_3D.cd(1)
hist1_3D.Draw("BOX2Z")
canvas_3D.cd(2)
hist2_3D.Draw("BOX2Z")
#legend.Draw("same")
#canvas.cd(2).SetLogx(1)
canvas_3D.cd(3)
hist3_3D.Draw("BOX2Z")

canvas_3D.Print(boson + "_boson_pt_jets_fuehrende_Ordnung_pt_DeltaPhi_3D.png")
#canvas.Print(boson + "_boson_pt_jets_fuehrende_Ordnung_pt_DeltaPhi_3D.pdf")
canvas_3D.Clear()
legend.Clear()
##########################################
legend.AddEntry(hist4_3D, "LO", "f")
legend.AddEntry(hist5_3D, "NLO", "f")

canvas_3D.Divide(2,2)
#canvas.cd(1).SetLogx(1)
#canvas.cd(1).SetLogy(1)
canvas_3D.cd(1)
hist4_3D.Draw("box2z")
canvas_3D.cd(2)
hist5_3D.Draw("box2z")
#legend.Draw("same")
#canvas.cd(2).SetLogx(1)
canvas_3D.cd(3)
hist6_3D.Draw("box2z")

canvas_3D.Print(boson + "_boson_pt_jets_fuehrende_Ordnung_pt_anzahl_3D.png")
#canvas.Print(boson + "_boson_pt_jets_fuehrende_Ordnung_pt_anzahl_3D.pdf")
canvas_3D.Clear()
legend.Clear()
############################################
legend.AddEntry(hist7_3D, "LO", "f")
legend.AddEntry(hist8_3D, "NLO", "f")


canvas_3D.Divide(2,2)
#canvas_3D.cd(1).SetLogx(1)
#canvas_3D.cd(1).SetLogy(1)
canvas_3D.cd(1)
hist7_3D.Draw("box2z")
canvas_3D.cd(2)
hist8_3D.Draw("box2z")
#legend.Draw("same")
#canvas.cd(2).SetLogx(1)
canvas_3D.cd(3)
hist9_3D.Draw("box2z")

canvas_3D.Print(boson + "_boson_pt_DeltaPhi_anzahl_3D.png")
#canvas.Print(boson + "_boson_pt_DeltaPhi_anzahl_3D.pdf")
canvas_3D.Clear()
legend.Clear()
################################################

#inklusiver Raum und Analysephasenraum

hist_ana=file_LO.Get(boson+"_boson_pt_ana")
hist2_ana=file_NLO.Get(boson+"_boson_pt_ana")
hist4_ana=file_LO.Get(boson + "_boson_pt_to1TeV_ana")
hist5_ana=file_NLO.Get(boson +"_boson_pt_to1TeV_ana")
hist7_ana=file_LO.Get(boson + "_boson_eta_ana")
hist8_ana=file_NLO.Get(boson + "_boson_eta_ana")
hist10_ana=file_LO.Get(boson + "_boson_phi_ana")
hist11_ana=file_NLO.Get(boson + "_boson_phi_ana")
hist13_ana=file_LO.Get(boson + "_jets_fuehrende_Ordnung_pt_ana")
hist14_ana=file_NLO.Get(boson + "_jets_fuehrende_Ordnung_pt_ana")
hist16_ana=file_LO.Get(boson + "_jets_fuehrende_Ordnung_eta_ana")
hist17_ana=file_NLO.Get(boson + "_jets_fuehrende_Ordnung_eta_ana")
hist19_ana=file_LO.Get(boson + "_jets_anzahl_ana")
hist20_ana=file_NLO.Get(boson + "_jets_anzahl_ana")
hist22_ana=file_LO.Get(boson + "_jets_HT_ana")
hist23_ana=file_NLO.Get(boson + "_jets_HT_ana")
hist25_ana=file_LO.Get(boson + "_boson_jets_fuehrende_Ordnung_DeltaPhi_ana")
hist26_ana=file_NLO.Get(boson + "_boson_jets_fuehrende_Ordnung_DeltaPhi_ana")
hist28_ana=file_LO.Get(boson + "_boson_transverse_mass_ana")
hist29_ana=file_NLO.Get(boson + "_boson_transverse_mass_ana")

#for i in (4,28):
#    j=i+1
#    k=j+1
#    histk_ana=histj_ana.Clone()
#    histk_ana.Divide(histi_ana)
#    histi_ana.SetLineColor(3)
#    histj_ana.SetLineColor(4)
#    histk_ana.SetLineColor(2)
#
#    legend.AddEntry(histi, "LO", "l")
#    legend.AddEntry(histj, "NLO", "l")
#    legend.AddEntry(histi_ana, "LO_ana", "l")
#    legend.AddEntry(histj_ana, "NLO_ana", "l")
#    legend2.AddEntry(histk, "inklusives sample", "l")
#    legend2.AddEntry(histk_ana, "Analysephasenraum", "l")
#    
#i+=3


hist3_ana=hist2_ana.Clone()
hist3_ana.Divide(hist_ana)
hist_ana.SetLineColor(3)
hist2_ana.SetLineColor(4)
hist3_ana.SetLineColor(2)

hist6_ana=hist5_ana.Clone()
hist6_ana.Divide(hist4_ana)
hist4_ana.SetLineColor(3)
hist5_ana.SetLineColor(4)
hist6_ana.SetLineColor(2)

hist9_ana=hist8_ana.Clone()
hist9_ana.Divide(hist7_ana)
hist7_ana.SetLineColor(3)
hist8_ana.SetLineColor(4)
hist9_ana.SetLineColor(2)
hist7.GetYaxis().SetRangeUser(0.1,10000)

hist12_ana=hist11_ana.Clone()
hist12_ana.Divide(hist10_ana)
hist10_ana.SetLineColor(3)
hist11_ana.SetLineColor(4)
hist12_ana.SetLineColor(2)
hist10.GetYaxis().SetRangeUser(0.1,10000)

hist15_ana=hist14_ana.Clone()
hist15_ana.Divide(hist13_ana)
hist13_ana.SetLineColor(3)
hist14_ana.SetLineColor(4)
hist15_ana.SetLineColor(2)

hist18_ana=hist17_ana.Clone()
hist18_ana.Divide(hist16_ana)
hist16_ana.SetLineColor(3)
hist17_ana.SetLineColor(4)
hist18_ana.SetLineColor(2)
hist16.GetYaxis().SetRangeUser(0.01,4000)

hist21_ana=hist20_ana.Clone()
hist21_ana.Divide(hist19_ana)
hist19_ana.SetLineColor(3)
hist20_ana.SetLineColor(4)
hist21_ana.SetLineColor(2)

hist24_ana=hist23_ana.Clone()
hist24_ana.Divide(hist22_ana)
hist22_ana.SetLineColor(3)
hist23_ana.SetLineColor(4)
hist24_ana.SetLineColor(2)

hist27_ana=hist26_ana.Clone()
hist27_ana.Divide(hist25_ana)
hist25_ana.SetLineColor(3)
hist26_ana.SetLineColor(4)
hist27_ana.SetLineColor(2)
hist25.GetYaxis().SetRangeUser(0.01,10000)

hist30_ana=hist29_ana.Clone()
hist30_ana.Divide(hist28_ana)
hist28_ana.SetLineColor(3)
hist29_ana.SetLineColor(4)
hist30_ana.SetLineColor(2)
hist28.GetYaxis().SetRangeUser(0.01,10000)



legend.AddEntry(hist, "LO", "l")
legend.AddEntry(hist2, "NLO", "l")
legend.AddEntry(hist_ana, "LO_ana", "l")
legend.AddEntry(hist2_ana, "NLO_ana", "l")
legend2.AddEntry(hist3, "inklusives sample", "l")
legend2.AddEntry(hist3_ana, "Analysephasenraum", "l")
canvas.Divide(1,2)
canvas.cd(1).SetLogy(1)
canvas.cd(1)
hist.Draw("histe")
hist2.Draw("histesame")
hist_ana.Draw("histesame")
hist2_ana.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist3.Draw("histe")
hist3_ana.Draw("histesame")
legend2.Draw("same")

canvas.Print(boson + "_boson_pt_ana_inkl.png")
#canvas.Print(boson + "_boson_pt_ana_inkl.pdf")
canvas.Clear()
legend.Clear()
legend2.Clear()

legend.AddEntry(hist4, "LO", "l")
legend.AddEntry(hist5, "NLO", "l")
legend.AddEntry(hist4_ana, "LO_ana", "l")
legend.AddEntry(hist5_ana, "NLO_ana", "l")
legend2.AddEntry(hist6, "inklusives sample", "l")
legend2.AddEntry(hist6_ana, "Analysephasenraum", "l")
canvas.Divide(1,2)
canvas.cd(1).SetLogy(1)
canvas.cd(1)
hist4.Draw("histe")
hist5.Draw("histesame")
hist4_ana.Draw("histesame")
hist5_ana.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist6.Draw("histe")
hist6_ana.Draw("histesame")
legend2.Draw("same")

canvas.Print(boson + "_boson_pt_to1TeV_ana_inkl.png")
#canvas.Print(boson + "_boson_pt_ana_inkl.pdf")
canvas.Clear()
legend.Clear()
legend2.Clear()

legend.AddEntry(hist7, "LO", "l")
legend.AddEntry(hist8, "NLO", "l")
legend.AddEntry(hist7_ana, "LO_ana", "l")
legend.AddEntry(hist8_ana, "NLO_ana", "l")
legend2.AddEntry(hist9, "inklusives sample", "l")
legend2.AddEntry(hist9_ana, "Analysephasenraum", "l")
canvas.Divide(1,2)
canvas.cd(1).SetLogy(1)
canvas.cd(1)
hist7.Draw("histe")
hist8.Draw("histesame")
hist7_ana.Draw("histesame")
hist8_ana.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist9.Draw("histe")
hist9_ana.Draw("histesame")
legend2.Draw("same")

canvas.Print(boson + "_boson_eta_ana_inkl.png")
#canvas.Print(boson + "_boson_pt_ana_inkl.pdf")
canvas.Clear()
legend.Clear()
legend2.Clear()

legend.AddEntry(hist10, "LO", "l")
legend.AddEntry(hist11, "NLO", "l")
legend.AddEntry(hist10_ana, "LO_ana", "l")
legend.AddEntry(hist11_ana, "NLO_ana", "l")
legend2.AddEntry(hist12, "inklusives sample", "l")
legend2.AddEntry(hist12_ana, "Analysephasenraum", "l")
canvas.Divide(1,2)
canvas.cd(1).SetLogy(1)
canvas.cd(1)
hist10.Draw("histe")
hist11.Draw("histesame")
hist10_ana.Draw("histesame")
hist11_ana.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist12.Draw("histe")
hist12_ana.Draw("histesame")
legend2.Draw("same")

canvas.Print(boson + "_boson_phi_ana_inkl.png")
#canvas.Print(boson + "_boson_pt_ana_inkl.pdf")
canvas.Clear()
legend.Clear()
legend2.Clear()


legend.AddEntry(hist13, "LO", "l")
legend.AddEntry(hist14, "NLO", "l")
legend.AddEntry(hist13_ana, "LO_ana", "l")
legend.AddEntry(hist14_ana, "NLO_ana", "l")
legend2.AddEntry(hist15, "inklusives sample", "l")
legend2.AddEntry(hist15_ana, "Analysephasenraum", "l")
canvas.Divide(1,2)
canvas.cd(1).SetLogy(1)
canvas.cd(1)
hist13.Draw("histe")
hist14.Draw("histesame")
hist13_ana.Draw("histesame")
hist14_ana.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist15.Draw("histe")
hist15_ana.Draw("histesame")
legend2.Draw("same")

canvas.Print(boson + "_jets_fuehrende_Ordnung_pt_ana_inkl.png")
#canvas.Print(boson + "_boson_pt_ana_inkl.pdf")
canvas.Clear()
legend.Clear()
legend2.Clear()

legend.AddEntry(hist16, "LO", "l")
legend.AddEntry(hist17, "NLO", "l")
legend.AddEntry(hist16_ana, "LO_ana", "l")
legend.AddEntry(hist17_ana, "NLO_ana", "l")
legend2.AddEntry(hist18, "inklusives sample", "l")
legend2.AddEntry(hist18_ana, "Analysephasenraum", "l")
canvas.Divide(1,2)
canvas.cd(1).SetLogy(1)
canvas.cd(1)
hist16.Draw("histe")
hist17.Draw("histesame")
hist16_ana.Draw("histesame")
hist17_ana.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist18.Draw("histe")
hist18_ana.Draw("histesame")
legend2.Draw("same")

canvas.Print(boson + "_jets_fuehrende_Ordnung_eta_ana_inkl.png")
#canvas.Print(boson + "_boson_pt_ana_inkl.pdf")
canvas.Clear()
legend.Clear()
legend2.Clear()

legend.AddEntry(hist19, "LO", "l")
legend.AddEntry(hist20, "NLO", "l")
legend.AddEntry(hist19_ana, "LO_ana", "l")
legend.AddEntry(hist20_ana, "NLO_ana", "l")
legend2.AddEntry(hist21, "inklusives sample", "l")
legend2.AddEntry(hist21_ana, "Analysephasenraum", "l")
canvas.Divide(1,2)
canvas.cd(1).SetLogy(1)
canvas.cd(1)
hist19.Draw("histe")
hist20.Draw("histesame")
hist19_ana.Draw("histesame")
hist20_ana.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist21.Draw("histe")
hist21_ana.Draw("histesame")
legend2.Draw("same")

canvas.Print(boson + "_jets_anzahl_ana_inkl.png")
#canvas.Print(boson + "_boson_pt_ana_inkl.pdf")
canvas.Clear()
legend.Clear()
legend2.Clear()

legend.AddEntry(hist22, "LO", "l")
legend.AddEntry(hist23, "NLO", "l")
legend.AddEntry(hist22_ana, "LO_ana", "l")
legend.AddEntry(hist23_ana, "NLO_ana", "l")
legend2.AddEntry(hist24, "inklusives sample", "l")
legend2.AddEntry(hist24_ana, "Analysephasenraum", "l")
canvas.Divide(1,2)
canvas.cd(1).SetLogy(1)
canvas.cd(1)
hist22.Draw("histe")
hist23.Draw("histesame")
hist22_ana.Draw("histesame")
hist23_ana.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist24.Draw("histe")
hist24_ana.Draw("histesame")
legend2.Draw("same")

canvas.Print(boson + "_jets_HT_ana_inkl.png")
#canvas.Print(boson + "_boson_pt_ana_inkl.pdf")
canvas.Clear()
legend.Clear()
legend2.Clear()

legend.AddEntry(hist25, "LO", "l")
legend.AddEntry(hist26, "NLO", "l")
legend.AddEntry(hist25_ana, "LO_ana", "l")
legend.AddEntry(hist26_ana, "NLO_ana", "l")
legend2.AddEntry(hist27, "inklusives sample", "l")
legend2.AddEntry(hist27_ana, "Analysephasenraum", "l")
canvas.Divide(1,2)
canvas.cd(1).SetLogy(1)
canvas.cd(1)
hist25.Draw("histe")
hist26.Draw("histesame")
hist25_ana.Draw("histesame")
hist26_ana.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist27.Draw("histe")
hist27_ana.Draw("histesame")
legend2.Draw("same")

canvas.Print(boson + "_boson_jets_fuehrende_Ordnung_DeltaPhi_ana_inkl.png")
#canvas.Print(boson + "_boson_pt_ana_inkl.pdf")
canvas.Clear()
legend.Clear()
legend2.Clear()

legend.AddEntry(hist28, "LO", "l")
legend.AddEntry(hist29, "NLO", "l")
legend.AddEntry(hist28_ana, "LO_ana", "l")
legend.AddEntry(hist29_ana, "NLO_ana", "l")
legend2.AddEntry(hist30, "inklusives sample", "l")
legend2.AddEntry(hist30_ana, "Analysephasenraum", "l")
canvas.Divide(1,2)
canvas.cd(1).SetLogy(1)
canvas.cd(1)
hist28.Draw("histe")
hist29.Draw("histesame")
hist28_ana.Draw("histesame")
hist29_ana.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist30.Draw("histe")
hist30_ana.Draw("histesame")
legend2.Draw("same")

canvas.Print(boson + "_boson_transverse_mass_ana_inkl.png")
#canvas.Print(boson + "_boson_pt_ana_inkl.pdf")
canvas.Clear()
legend.Clear()
legend2.Clear()




############################################

#Analysephasenraum

hist=file_LO.Get(boson+"_boson_pt_ana")
hist2=file_NLO.Get(boson+"_boson_pt_ana")
hist4=file_LO.Get(boson + "_boson_pt_to1TeV_ana")
hist5=file_NLO.Get(boson +"_boson_pt_to1TeV_ana")
hist7=file_LO.Get(boson + "_boson_eta_ana")
hist8=file_NLO.Get(boson + "_boson_eta_ana")
hist10=file_LO.Get(boson + "_boson_phi_ana")
hist11=file_NLO.Get(boson + "_boson_phi_ana")
hist13=file_LO.Get(boson + "_jets_fuehrende_Ordnung_pt_ana")
hist14=file_NLO.Get(boson + "_jets_fuehrende_Ordnung_pt_ana")
hist16=file_LO.Get(boson + "_jets_fuehrende_Ordnung_eta_ana")
hist17=file_NLO.Get(boson + "_jets_fuehrende_Ordnung_eta_ana")
hist19=file_LO.Get(boson + "_jets_anzahl_ana")
hist20=file_NLO.Get(boson + "_jets_anzahl_ana")
hist22=file_LO.Get(boson + "_jets_HT_ana")
hist23=file_NLO.Get(boson + "_jets_HT_ana")
hist25=file_LO.Get(boson + "_boson_jets_fuehrende_Ordnung_DeltaPhi_ana")
hist26=file_NLO.Get(boson + "_boson_jets_fuehrende_Ordnung_DeltaPhi_ana")
hist28=file_LO.Get(boson + "_boson_transverse_mass_ana")
hist29=file_NLO.Get(boson + "_boson_transverse_mass_ana")
hist1_2D=file_LO.Get(boson + "_boson_jets_fuehrende_Ordnung_pt_2D_ana")
hist2_2D=file_NLO.Get(boson + "_boson_jets_fuehrende_Ordnung_pt_2D_ana")
hist4_2D=file_LO.Get(boson + "_boson_pt_DeltaPhi_2D_ana")
hist5_2D=file_NLO.Get(boson + "_boson_pt_DeltaPhi_2D_ana")
hist7_2D=file_LO.Get(boson + "_jets_fuehrende_Ordnung_pt_DeltaPhi_2D_ana")
hist8_2D=file_NLO.Get(boson + "_jets_fuehrende_Ordnung_pt_DeltaPhi_2D_ana")
hist10_2D=file_LO.Get(boson + "_jets_anzahl_HT_2D_ana")
hist11_2D=file_NLO.Get(boson + "_jets_anzahl_HT_2D_ana")
hist13_2D=file_LO.Get(boson + "_boson_transverse_mass_pt_2D_ana")
hist14_2D=file_NLO.Get(boson + "_boson_transverse_mass_pt_2D_ana")
hist16_2D=file_LO.Get(boson + "_boson_transverse_mass_phizwlundnu_2D_ana")
hist17_2D=file_NLO.Get(boson + "_boson_transverse_mass_phizwlundnu_2D_ana")
hist1_3D=file_LO.Get(boson + "_boson_pt_jets_fuehrende_Ordnung_pt_DeltaPhi_3D_ana")
hist2_3D=file_NLO.Get(boson + "_boson_pt_jets_fuehrende_Ordnung_pt_DeltaPhi_3D_ana")
hist4_3D=file_LO.Get(boson+ "_boson_pt_jets_fuehrende_Ordnung_pt_anzahl_3D_ana")
hist5_3D=file_NLO.Get(boson+ "_boson_pt_jets_fuehrende_Ordnung_pt_anzahl_3D_ana")
hist7_3D=file_LO.Get(boson + "_boson_pt_DeltaPhi_anzahl_3D_ana")
hist8_3D=file_NLO.Get(boson + "_boson_pt_DeltaPhi_anzahl_3D_ana")

##################################################

hist3=hist2.Clone()
hist3.Divide(hist)
hist.GetXaxis().SetTitle("transversaler Impuls in GeV")
hist.GetYaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist.GetXaxis().SetRangeUser(250.0,1000.0)
#hist.GetYaxis().SetRangeUser(0.00000001,100000000)
hist.GetXaxis().CenterTitle()
hist.GetYaxis().CenterTitle()
hist.SetLineColor(1)
hist2.SetLineColor(2)
hist3.GetXaxis().SetTitle("transversaler Impuls in GeV")
hist3.GetYaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist3.GetXaxis().SetRangeUser(250.0,1000.0)
hist3.GetXaxis().CenterTitle()
hist3.GetYaxis().CenterTitle()
hist3.GetYaxis().SetRangeUser(0,2)
hist.SetTitle("Transversalimpuls des "+ boson+ " Bosons")
hist3.SetTitle("")

hist6=hist5.Clone()
hist6.Divide(hist4)
hist4.GetXaxis().SetTitle("transversaler Impuls in GeV")
hist4.GetYaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")    
hist4.GetXaxis().CenterTitle()
hist4.GetYaxis().CenterTitle()
hist4.GetXaxis().SetRangeUser(250.0,1000.0)
hist4.SetLineColor(1)
hist5.SetLineColor(2)
hist6.GetXaxis().SetTitle("transversaler Impuls in GeV")
hist6.GetYaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist6.GetXaxis().CenterTitle()
hist6.GetYaxis().CenterTitle() 
hist6.GetYaxis().SetRangeUser(0,2)
hist6.GetXaxis().SetRangeUser(250.0,1000.0)
hist4.SetTitle("Transversalimpuls des "+ boson+ " Bosons")
hist6.SetTitle("")

hist9=hist8.Clone()
hist9.Divide(hist7)
hist7.GetXaxis().SetTitle("Pseudorapiditaet")
hist7.GetYaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")    
hist7.GetXaxis().CenterTitle()
hist7.GetYaxis().CenterTitle()
hist7.SetLineColor(1)
hist8.SetLineColor(2)
hist7.GetYaxis().SetRangeUser(0,3.5)
hist7.GetXaxis().SetRangeUser(-3.14,3.14)
#hist7.GetXaxis().SetRangeUser(-20,20)
hist9.GetXaxis().SetTitle("Pseudorapiditaet")
hist9.GetYaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist9.GetXaxis().CenterTitle()
hist9.GetYaxis().CenterTitle()
hist9.GetXaxis().SetRangeUser(-3.14,3.14)
hist9.GetYaxis().SetRangeUser(0,2)
hist7.SetTitle("Pseudorapiditaet des "+ boson+ " Bosons")
hist9.SetTitle("")

hist12=hist11.Clone()
hist12.Divide(hist10)
hist10.GetXaxis().SetTitle("Azimutalwinkel")
hist10.GetYaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")    
hist10.GetXaxis().CenterTitle()
hist10.GetYaxis().CenterTitle()
hist10.SetLineColor(1)
hist11.SetLineColor(2)
hist10.GetYaxis().SetRangeUser(0.35,0.85)
hist12.GetXaxis().SetTitle("Azimutalwinkel")
hist12.GetYaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist12.GetXaxis().CenterTitle()
hist12.GetYaxis().CenterTitle()
hist12.GetYaxis().SetRangeUser(0,2)
hist10.SetTitle("Azimutalwinkel des "+ boson+ " Bosons")
hist12.SetTitle("")

hist15=hist14.Clone()
hist15.Divide(hist13)
hist13.GetXaxis().SetTitle("transversaler Impuls in GeV")
hist13.GetYaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist13.GetXaxis().CenterTitle()
hist13.GetYaxis().CenterTitle()
hist13.GetXaxis().SetRangeUser(100.0,1000.0)
hist13.SetLineColor(1)
hist14.SetLineColor(2)
hist15.GetXaxis().SetTitle("transversaler Impuls in GeV")
hist15.GetYaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist15.GetXaxis().CenterTitle()
hist15.GetYaxis().CenterTitle()
hist15.GetXaxis().SetRangeUser(100.0,1000.0)
hist15.GetYaxis().SetRangeUser(0,2)
hist13.SetTitle("Transversalimpuls des fuehrenden Jets")
hist15.SetTitle("")

hist18=hist17.Clone()
hist18.Divide(hist16)
hist16.GetXaxis().SetTitle("Pseudorapiditaet")
hist16.GetYaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")    
hist16.GetXaxis().CenterTitle()
hist16.GetYaxis().CenterTitle()
hist16.GetXaxis().SetRangeUser(-2.4,2.4)
hist16.GetYaxis().SetRangeUser(0,4)
hist16.SetLineColor(1)
hist17.SetLineColor(2)
hist18.GetXaxis().SetRangeUser(-2.4,2.4)
hist18.GetXaxis().SetTitle("Pseudorapiditaet")
hist18.GetYaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist18.GetXaxis().CenterTitle()
hist18.GetYaxis().CenterTitle()
hist18.GetYaxis().SetRangeUser(0,2)
hist16.SetTitle("Pseudorapiditaet des fuehrenden Jets")
hist18.SetTitle("")

hist21=hist20.Clone()
hist21.Divide(hist19)
hist19.GetXaxis().SetTitle("Anzahl der Jets")
hist19.GetYaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")    
hist19.GetXaxis().CenterTitle()
hist19.GetYaxis().CenterTitle()
hist19.SetLineColor(1)
hist20.SetLineColor(2)
hist19.GetXaxis().SetRangeUser(1,12)
hist21.GetXaxis().SetRangeUser(1,12)
hist21.GetXaxis().SetTitle("Anzahl der Jets")
hist21.GetYaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist21.GetXaxis().CenterTitle()
hist21.GetYaxis().CenterTitle()
hist21.GetYaxis().SetRangeUser(0,2)
hist19.SetTitle("Anzahl der Jets mit pt>=30 GeV,|eta|<=2.4")
hist21.SetTitle("")

hist24=hist23.Clone()
hist24.Divide(hist22)
hist22.GetXaxis().SetTitle("Summe der Transversalimpulse aller Jets in GeV")
hist22.GetYaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist22.GetXaxis().CenterTitle()
hist22.GetYaxis().CenterTitle()
hist22.SetLineColor(1)
hist23.SetLineColor(2)
hist24.GetXaxis().SetTitle("Summe der Transversalimpulse aller Jets in GeV")
hist24.GetYaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist24.GetXaxis().CenterTitle()
hist24.GetYaxis().CenterTitle()
hist24.GetYaxis().SetRangeUser(0,2)
hist22.SetTitle("Summe der Transversalimpulse aller Jets mit pt>=30 GeV,|eta|<=2.4")
hist24.SetTitle("")

hist27=hist26.Clone()
hist27.Divide(hist25)
hist25.GetXaxis().SetTitle("Betrag des Azimutalwinkels zwischen "+boson+" Boson und fuehrendem Jet")
hist25.GetYaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist25.GetXaxis().CenterTitle()
hist25.GetYaxis().CenterTitle()
hist25.GetXaxis().SetRangeUser(1.57,3.14)
hist25.GetYaxis().SetRangeUser(0,12)
hist25.SetLineColor(1)
hist26.SetLineColor(2)
hist27.GetXaxis().SetTitle("Betrag des Azimutalwinkels zwischen "+boson+" Boson und fuehrendem Jet")
hist27.GetYaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist27.GetXaxis().CenterTitle()
hist27.GetYaxis().CenterTitle()
hist27.GetXaxis().SetRangeUser(1.57,3.14)
hist27.GetYaxis().SetRangeUser(0,2)
hist27.GetYaxis().SetRangeUser(0,2)
hist25.SetTitle("Betrag des Azimutalwinkels zwischen "+boson+ " Boson und fuehrendem Jet")
hist27.SetTitle("")

hist30=hist29.Clone()
hist30.Divide(hist28)
hist28.GetXaxis().SetTitle("transversale Masse des W Bosons in GeV")
hist28.GetYaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
#hist28.GetXaxis().SetRangeUser(30.0,1000.0)
#hist.GetYaxis().SetRangeUser(0.00000001,100000000)
hist28.GetXaxis().CenterTitle()
hist28.GetYaxis().CenterTitle()
hist28.SetLineColor(1)
hist29.SetLineColor(2)
hist30.GetXaxis().SetTitle("transversale Masse des W Bosons in GeV")
hist30.GetYaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
#hist30.GetXaxis().SetRangeUser(30.0,1000.0)
hist30.GetXaxis().CenterTitle()
hist30.GetYaxis().CenterTitle()
hist30.GetYaxis().SetRangeUser(0,2)
hist28.SetTitle("Transversale Masse des W Bosons")
hist30.SetTitle("")


hist3_2D=hist2_2D.Clone()
hist3_2D.Divide(hist1_2D)
hist1_2D.GetXaxis().SetTitle("transversaler Impuls des "+boson+" Bosons in GeV")
hist1_2D.GetYaxis().SetTitle("transversaler Impuls des fuehrenden Jets in GeV")
hist1_2D.GetZaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist1_2D.GetXaxis().CenterTitle()
hist1_2D.GetYaxis().CenterTitle()
hist1_2D.GetZaxis().CenterTitle()
hist1_2D.GetXaxis().SetRangeUser(250,1000)
hist1_2D.GetYaxis().SetRangeUser(100,1000)
hist2_2D.GetXaxis().SetTitle("transversaler Impuls des "+boson+" Bosons in GeV")
hist2_2D.GetYaxis().SetTitle("transversaler Impuls des fuehrenden Jets in GeV")
hist2_2D.GetZaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist2_2D.GetXaxis().CenterTitle()
hist2_2D.GetYaxis().CenterTitle()
hist2_2D.GetZaxis().CenterTitle()
hist2_2D.GetXaxis().SetRangeUser(250,1000)
hist2_2D.GetYaxis().SetRangeUser(100,1000)
hist3_2D.GetXaxis().SetTitle("transversaler Impuls des "+boson+" Bosons in GeV")
hist3_2D.GetYaxis().SetTitle("transversaler Impuls des fuehrenden Jets in GeV")
hist3_2D.GetZaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist3_2D.GetXaxis().CenterTitle()
hist3_2D.GetYaxis().CenterTitle()
hist3_2D.GetZaxis().CenterTitle()
hist3_2D.GetXaxis().SetRangeUser(250,1000)
hist3_2D.GetYaxis().SetRangeUser(100,1000)
hist3_2D.GetZaxis().SetRangeUser(0,2)
hist1_2D.SetTitle("LO")
hist2_2D.SetTitle("NLO")
hist3_2D.SetTitle("Verhaeltnis NLO zu LO")

hist6_2D=hist5_2D.Clone()
hist6_2D.Divide(hist4_2D)
hist4_2D.GetXaxis().SetTitle("transversaler Impuls des "+boson+" Bosons in GeV")
hist4_2D.GetYaxis().SetTitle("Azimutalwinkel zwischen "+boson+" Boson und fuehrendem Jet")
hist4_2D.GetZaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist4_2D.GetZaxis().CenterTitle()
hist4_2D.GetXaxis().CenterTitle()
hist4_2D.GetYaxis().CenterTitle()
hist4_2D.GetXaxis().SetRangeUser(250,1000)
hist4_2D.GetYaxis().SetRangeUser(1.57,3.14)
hist5_2D.GetXaxis().SetTitle("transversaler Impuls des "+boson+" Bosons in GeV")
hist5_2D.GetYaxis().SetTitle("Azimutalwinkel zwischen "+boson+" Boson und fuehrendem Jet")
hist5_2D.GetZaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist5_2D.GetZaxis().CenterTitle()
hist5_2D.GetXaxis().CenterTitle()
hist5_2D.GetYaxis().CenterTitle()
hist5_2D.GetXaxis().SetRangeUser(250,1000)
hist5_2D.GetYaxis().SetRangeUser(1.57,3.14)
hist6_2D.GetXaxis().SetTitle("transversaler Impuls des "+boson+" Bosons in GeV")
hist6_2D.GetYaxis().SetTitle("Azimutalwinkel zwischen "+boson+" Boson und fuehrendem Jet")
hist6_2D.GetZaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist6_2D.GetZaxis().CenterTitle()
hist6_2D.GetXaxis().CenterTitle()
hist6_2D.GetYaxis().CenterTitle() 
hist6_2D.GetXaxis().SetRangeUser(250,1000)
hist6_2D.GetYaxis().SetRangeUser(1.57,3.14)
hist6_2D.GetZaxis().SetRangeUser(0,2)
hist4_2D.SetTitle("LO")
hist5_2D.SetTitle("NLO")
hist6_2D.SetTitle("Verhaeltnis NLO zu LO")

hist9_2D=hist8_2D.Clone()
hist9_2D.Divide(hist7_2D)
hist7_2D.GetXaxis().SetTitle("transversaler Impuls des fuehrenden Jets in GeV")
hist7_2D.GetYaxis().SetTitle("Azimutalwinkel zwischen "+boson+" Boson und fuehrendem Jet")
hist7_2D.GetZaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist7_2D.GetZaxis().CenterTitle()
hist7_2D.GetXaxis().CenterTitle()
hist7_2D.GetYaxis().CenterTitle()
hist7_2D.GetXaxis().SetRangeUser(100,1000)
hist7_2D.GetYaxis().SetRangeUser(1.57,3.14)
hist8_2D.GetXaxis().SetTitle("transversaler Impuls des fuehrenden Jets in GeV")
hist8_2D.GetYaxis().SetTitle("Azimutalwinkel zwischen "+boson+" Boson und fuehrendem Jet") 
hist8_2D.GetZaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist8_2D.GetZaxis().CenterTitle()
hist8_2D.GetXaxis().CenterTitle()
hist8_2D.GetYaxis().CenterTitle()
hist8_2D.GetXaxis().SetRangeUser(100,1000)
hist8_2D.GetYaxis().SetRangeUser(1.57,3.14)
hist9_2D.GetXaxis().SetTitle("transversaler Impuls des fuehrenden Jets in GeV")
hist9_2D.GetYaxis().SetTitle("Azimutalwinkel zwischen "+boson+" Boson und fuehrendem Jet")
hist9_2D.GetZaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist9_2D.GetZaxis().CenterTitle()
hist9_2D.GetXaxis().CenterTitle()
hist9_2D.GetYaxis().CenterTitle()
hist9_2D.GetXaxis().SetRangeUser(100,1000)
hist9_2D.GetYaxis().SetRangeUser(1.57,3.14)
hist9_2D.GetZaxis().SetRangeUser(0,2)
hist7_2D.SetTitle("LO")
hist8_2D.SetTitle("NLO")
hist9_2D.SetTitle("Verhaeltnis NLO zu LO")

hist12_2D=hist11_2D.Clone()
hist12_2D.Divide(hist10_2D)
hist10_2D.GetXaxis().SetTitle("Anzahl der Jets mit pt>=30 GeV,|eta|<=2.4")
hist10_2D.GetYaxis().SetTitle("Summe der pt aller Jets in GeV mit pt>=30 GeV,|eta|<=2.4")
hist10_2D.GetZaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist10_2D.GetZaxis().CenterTitle()
hist10_2D.GetXaxis().CenterTitle()
hist10_2D.GetYaxis().CenterTitle()
hist10_2D.GetXaxis().SetRangeUser(1,12)
hist11_2D.GetXaxis().SetTitle("Anzahl der Jets mit pt>=30 GeV,|eta|<=2.4")
hist11_2D.GetYaxis().SetTitle("Summe der pt aller Jets in GeV mit pt>=30 GeV,|eta|<=2.4")   
hist11_2D.GetZaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist11_2D.GetZaxis().CenterTitle()
hist11_2D.GetXaxis().CenterTitle()
hist11_2D.GetYaxis().CenterTitle()
hist11_2D.GetXaxis().SetRangeUser(1,12)
hist12_2D.GetXaxis().SetTitle("Anzahl der Jets mit pt>=30 GeV,|eta|<=2.4")
hist12_2D.GetYaxis().SetTitle("Summe der pt aller Jets in GeV mit pt>=30 GeV,|eta|<=2.4")
hist12_2D.GetZaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist12_2D.GetZaxis().CenterTitle()
hist12_2D.GetXaxis().CenterTitle()
hist12_2D.GetYaxis().CenterTitle()
hist12_2D.GetXaxis().SetRangeUser(1,12)
hist12_2D.GetZaxis().SetRangeUser(0,2)
hist10_2D.SetTitle("LO")
hist11_2D.SetTitle("NLO")
hist12_2D.SetTitle("Verhaeltnis NLO zu LO")

hist15_2D=hist14_2D.Clone()
hist15_2D.Divide(hist13_2D)
hist13_2D.GetXaxis().SetTitle("transversale Masse des W Bosons in GeV")
hist13_2D.GetYaxis().SetTitle("transversaler Impuls des W Bosons in GeV")
hist13_2D.GetZaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist13_2D.GetZaxis().CenterTitle()
hist13_2D.GetXaxis().CenterTitle()
hist13_2D.GetYaxis().CenterTitle()
hist13_2D.GetYaxis().SetRangeUser(250,1000)
hist14_2D.GetXaxis().SetTitle("transversale Masse des W Bosons in GeV")
hist14_2D.GetYaxis().SetTitle("transversaler Impuls des W Bosons in GeV")
hist14_2D.GetZaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist14_2D.GetZaxis().CenterTitle()
hist14_2D.GetXaxis().CenterTitle()
hist14_2D.GetYaxis().CenterTitle()
hist14_2D.GetYaxis().SetRangeUser(250,1000)
hist15_2D.GetXaxis().SetTitle("transversale Masse des W Bosons in GeV")
hist15_2D.GetYaxis().SetTitle("transversaler Impuls des W Bosons in GeV")
hist15_2D.GetZaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist15_2D.GetZaxis().CenterTitle()
hist15_2D.GetXaxis().CenterTitle()
hist15_2D.GetYaxis().CenterTitle()
hist15_2D.GetYaxis().SetRangeUser(250,1000)
hist15_2D.GetZaxis().SetRangeUser(0,2)
hist13_2D.SetTitle("LO")
hist14_2D.SetTitle("NLO")
hist15_2D.SetTitle("Verhaeltnis NLO zu LO")

hist18_2D=hist17_2D.Clone()
hist18_2D.Divide(hist16_2D)
hist16_2D.GetXaxis().SetTitle("transversale Masse des W Bosons in GeV")
hist16_2D.GetYaxis().SetTitle("Azimutalwinkel zwischen geladenem Lepton und Neutrino") 
hist16_2D.GetZaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist16_2D.GetZaxis().CenterTitle()
hist16_2D.GetXaxis().CenterTitle()
hist16_2D.GetYaxis().CenterTitle()
hist17_2D.GetXaxis().SetTitle("transversale Masse des W Bosons in GeV")
hist17_2D.GetYaxis().SetTitle("Azimutalwinkel zwischen geladenem Lepton und Neutrino")  
hist17_2D.GetZaxis().SetTitle("Wirkungsquerschnitt in pb pro Bin")
hist17_2D.GetZaxis().CenterTitle()
hist17_2D.GetXaxis().CenterTitle()
hist17_2D.GetYaxis().CenterTitle()
hist18_2D.GetXaxis().SetTitle("transversale Masse des W Bosons in GeV")
hist18_2D.GetYaxis().SetTitle("Azimutalwinkel zwischen geladenem Lepton und Neutrino")
hist18_2D.GetZaxis().SetTitle("Wirkungsquerschnittsverhaeltnis NLO/LO")
hist18_2D.GetZaxis().CenterTitle()
hist18_2D.GetXaxis().CenterTitle()
hist18_2D.GetYaxis().CenterTitle()
hist18_2D.GetZaxis().SetRangeUser(0,2)
hist16_2D.SetTitle("LO")
hist17_2D.SetTitle("NLO")
hist18_2D.SetTitle("Verhaeltnis NLO zu LO")

hist3_3D=hist2_3D.Clone()
hist3_3D.Divide(hist1_3D)
hist1_3D.GetXaxis().SetTitle("transversaler Impuls des "+boson+" Bosons in GeV")
hist1_3D.GetYaxis().SetTitle("transversaler Impuls des fuehrenden Jets in GeV ")
hist1_3D.GetZaxis().SetTitle("Azimutalwinkel zwischen "+boson+" Boson und fuehrendem Jet")
hist1_3D.GetXaxis().CenterTitle()
hist1_3D.GetYaxis().CenterTitle()
hist1_3D.GetZaxis().CenterTitle()
hist1_3D.GetXaxis().SetRangeUser(250,1000)
hist1_3D.GetYaxis().SetRangeUser(100,1000)
hist1_3D.GetZaxis().SetRangeUser(1.57,3.14)
hist2_3D.GetXaxis().SetTitle("transversaler Impuls des "+boson+" Bosons in GeV")
hist2_3D.GetYaxis().SetTitle("transversaler Impuls in GeV vom fuehrenden Jet")
hist2_3D.GetZaxis().SetTitle("Azimutalwinkel zwischen "+boson+" Boson und fuehrendem Jet")
hist2_3D.GetXaxis().CenterTitle()
hist2_3D.GetYaxis().CenterTitle()
hist2_3D.GetZaxis().CenterTitle()
hist2_3D.GetXaxis().SetRangeUser(250,1000)
hist2_3D.GetYaxis().SetRangeUser(100,1000)
hist2_3D.GetZaxis().SetRangeUser(1.57,3.14)
hist3_3D.GetXaxis().SetTitle("transversaler Impuls des "+boson+" Bosons in GeV")
hist3_3D.GetYaxis().SetTitle("transversaler Impuls des fuehrenden Jets in GeV ")
hist3_3D.GetZaxis().SetTitle("Azimutalwinkel zwischen "+boson+" Boson und fuehrendem Jet")
hist3_3D.GetXaxis().CenterTitle()
hist3_3D.GetYaxis().CenterTitle()
hist3_3D.GetZaxis().CenterTitle()
hist3_3D.GetXaxis().SetRangeUser(250,1000)
hist3_3D.GetYaxis().SetRangeUser(100,1000)
hist3_3D.GetZaxis().SetRangeUser(1.57,3.14)
hist1_3D.SetTitle("LO")
hist2_3D.SetTitle("NLO")
hist3_3D.SetTitle("Verhaeltnis NLO zu LO")

hist6_3D=hist5_3D.Clone()
hist6_3D.Divide(hist4_3D)
hist4_3D.GetXaxis().SetTitle("transversaler Impuls des "+boson+" Bosons in GeV")
hist4_3D.GetYaxis().SetTitle("transversaler Impuls des fuehrenden Jets in GeV")
hist4_3D.GetZaxis().SetTitle("Anzahl der Jets mit pt>=30 GeV,|eta|<=2.4") 
hist4_3D.GetXaxis().SetRangeUser(250,1000)
hist4_3D.GetYaxis().SetRangeUser(100,1000)
hist4_3D.GetZaxis().SetRangeUser(1,12)
hist4_3D.GetXaxis().CenterTitle()
hist4_3D.GetYaxis().CenterTitle()
hist4_3D.GetZaxis().CenterTitle()
hist5_3D.GetXaxis().SetTitle("transversaler Impuls des "+boson+" Bosons in GeV")
hist5_3D.GetYaxis().SetTitle("transversaler Impuls des fuehrenden Jets in GeV")
hist5_3D.GetZaxis().SetTitle("Anzahl der Jets mit pt>=30 GeV,|eta|<=2.4")    
hist5_3D.GetXaxis().CenterTitle()
hist5_3D.GetYaxis().CenterTitle()
hist5_3D.GetZaxis().CenterTitle()
hist5_3D.GetXaxis().SetRangeUser(250,1000)
hist5_3D.GetYaxis().SetRangeUser(100,1000)
hist5_3D.GetZaxis().SetRangeUser(1,12)
hist6_3D.GetXaxis().SetTitle("transversaler Impuls des "+boson+" Bosons in GeV")
hist6_3D.GetYaxis().SetTitle("transversaler Impuls des fuehrenden Jets in GeV")
hist6_3D.GetZaxis().SetTitle("Anzahl der Jets mit pt>=30 GeV,|eta|<=2.4")
hist6_3D.GetXaxis().CenterTitle()
hist6_3D.GetYaxis().CenterTitle()
hist6_3D.GetZaxis().CenterTitle()
hist6_3D.GetXaxis().SetRangeUser(250,1000)
hist6_3D.GetYaxis().SetRangeUser(100,1000)
hist6_3D.GetZaxis().SetRangeUser(1,12)
hist4_3D.SetTitle("LO")
hist5_3D.SetTitle("NLO")
hist6_3D.SetTitle("Verhaeltnis NLO zu LO")

hist9_3D=hist8_3D.Clone()
hist9_3D.Divide(hist7_3D)
hist7_3D.GetXaxis().SetTitle("transversaler Impuls des "+boson+" Bosons in GeV")
hist7_3D.GetYaxis().SetTitle("Azimutalwinkel zwischen "+boson+" Boson und fuehrendem Jet")
hist7_3D.GetZaxis().SetTitle("Anzahl der Jets mit pt>=30 GeV,|eta|<=2.4")
hist7_3D.GetXaxis().CenterTitle()
hist7_3D.GetYaxis().CenterTitle()
hist7_3D.GetZaxis().CenterTitle()
hist7_3D.GetXaxis().SetRangeUser(250,1000)
hist7_3D.GetYaxis().SetRangeUser(1.57,3.14)
hist7_3D.GetZaxis().SetRangeUser(1,12)
hist8_3D.GetXaxis().SetTitle("transversaler Impuls des "+boson+" Bosons in GeV")
hist8_3D.GetYaxis().SetTitle("Azimutalwinkel zwischen "+boson+" Boson und fuehrendem Jet")
hist8_3D.GetZaxis().SetTitle("Anzahl der Jets mit pt>=30 GeV,|eta|<=2.4")
hist8_3D.GetXaxis().CenterTitle()
hist8_3D.GetYaxis().CenterTitle()
hist8_3D.GetZaxis().CenterTitle()
hist8_3D.GetXaxis().SetRangeUser(250,1000)
hist8_3D.GetYaxis().SetRangeUser(1.57,3.14)
hist8_3D.GetZaxis().SetRangeUser(1,12)
hist9_3D.GetXaxis().SetTitle("transversaler Impuls in GeV vom fuehrendem Jet")
hist9_3D.GetYaxis().SetTitle("Azimutalwinkel zwischen "+boson+" Boson und fuehrendem Jet")
hist9_3D.GetZaxis().SetTitle("Anzahl der Jets mit pt>=30 GeV,|eta|<=2.4")
hist9_3D.GetXaxis().CenterTitle()
hist9_3D.GetYaxis().CenterTitle()
hist9_3D.GetZaxis().CenterTitle()
hist9_3D.GetXaxis().SetRangeUser(250,1000)
hist9_3D.GetYaxis().SetRangeUser(1.57,3.14)
hist9_3D.GetZaxis().SetRangeUser(1,12)
hist7_3D.SetTitle("LO")
hist8_3D.SetTitle("NLO")
hist9_3D.SetTitle("Verhaeltnis NLO zu LO")
########################################
legend.AddEntry(hist, "LO", "l")
legend.AddEntry(hist2, "NLO", "l")

canvas.Divide(1,2)
canvas.cd(1).SetLogy(1)
canvas.cd(1)
hist.Draw("histe")
hist2.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist3.Draw("histe")

canvas.Print(boson + "_boson_pt_ana.png")
#canvas.Print(boson + "_boson_pt.pdf")
canvas.Clear()
legend.Clear()
#########################################
legend.AddEntry(hist4, "LO", "l")
legend.AddEntry(hist5, "NLO", "l")

canvas.Divide(1,2)
canvas.cd(1).SetLogy(1)
canvas.cd(1)
hist4.Draw("histe")
hist5.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist6.Draw("histe")

canvas.Print(boson + "_boson_pt_to1TeV_ana.png")
#canvas.Print(boson + "_boson_pt_to1TeV.pdf")
canvas.Clear()
legend.Clear()
###########################################
legend.AddEntry(hist7, "LO", "l")
legend.AddEntry(hist8, "NLO", "l")

canvas.Divide(1,2)
canvas.cd(1)
hist7.Draw("histe")
hist8.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist9.Draw("histe")

canvas.Print(boson + "_boson_eta_ana.png")
#canvas.Print(boson + "_boson_eta.pdf")
canvas.Clear()
legend.Clear()
################################################
legend.AddEntry(hist10, "LO", "l")
legend.AddEntry(hist11, "NLO", "l")

canvas.Divide(1,2)
canvas.cd(1)
hist10.Draw("histe")
hist11.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist12.Draw("histe")

canvas.Print(boson + "_boson_phi_ana.png")
#canvas.Print(boson + "_boson_phi.pdf")
canvas.Clear()
legend.Clear()
###########################################
legend.AddEntry(hist13, "LO", "l")
legend.AddEntry(hist14, "NLO", "l")

canvas.Divide(1,2)
canvas.cd(1).SetLogy(1)
canvas.cd(1)
hist13.Draw("histe")
hist14.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist15.Draw("histe")

canvas.Print(boson + "_jets_fuehrende_Ordnung_pt_ana.png")
#canvas.Print(boson + "_jets_fuehrende_Ordnung_pt.pdf")
canvas.Clear()
legend.Clear()
############################################
legend.AddEntry(hist16, "LO", "l")
legend.AddEntry(hist17, "NLO", "l")

canvas.Divide(1,2)
canvas.cd(1)
hist16.Draw("histe")
hist17.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist18.Draw("histe")

canvas.Print(boson + "_jets_fuehrende_Ordnung_eta_ana.png")
#canvas.Print(boson + "_jets_fuehrende_Ordnung_eta.pdf")
canvas.Clear()
legend.Clear()
############################################
legend.AddEntry(hist19, "LO", "l")
legend.AddEntry(hist20, "NLO", "l")

canvas.Divide(1,2)
canvas.cd(1)
canvas.cd(1).SetLogy(1)
hist19.Draw("histe")
hist20.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist21.Draw("histe")

canvas.Print(boson + "_jets_anzahl_ana.png")
#canvas.Print(boson + "_jets_anzahl.pdf")
canvas.Clear()
legend.Clear()
##############################################
legend.AddEntry(hist22, "LO", "l")
legend.AddEntry(hist23, "NLO", "l")

canvas.Divide(1,2)
canvas.cd(1).SetLogy(1)
canvas.cd(1)
hist22.Draw("histe")
hist23.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist24.Draw("histe")

canvas.Print(boson + "_jets_HT_ana.png")
#canvas.Print(boson + "_jets_HT.pdf")
canvas.Clear()
legend.Clear()
###########################################
legend.AddEntry(hist25, "LO", "l")
legend.AddEntry(hist26, "NLO", "l")

canvas.Divide(1,2)
#canvas.cd(1).SetLogy(1)
canvas.cd(1)
hist25.Draw("histe")
hist26.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist27.Draw("histe")

canvas.Print(boson + "_boson_jets_fuehrende_Ordnung_DeltaPhi_ana.png")
#canvas.Print(boson + "_boson_jets_fuehrende_Ordnung_DeltaPhi.pdf")
canvas.Clear()
legend.Clear()
###########################################
legend.AddEntry(hist28, "LO", "l")
legend.AddEntry(hist29, "NLO", "l")

canvas.Divide(1,2)
canvas.cd(1).SetLogy(1)
canvas.cd(1)
hist28.Draw("histe")
hist29.Draw("histesame")
legend.Draw("same")
canvas.cd(2)
hist30.Draw("histe")

canvas.Print(boson + "_boson_transverse_mass_ana.png")
#canvas.Print(boson + "_boson_transverse_mass.pdf")
canvas.Clear()
legend.Clear()
##########################################
legend.AddEntry(hist1_2D, "LO", "f")
legend.AddEntry(hist2_2D, "NLO", "f")

canvas.Divide(1,3)
canvas.cd(1).SetLogz(1)
canvas.cd(1)
ROOT.gPad.SetRightMargin(0.2)
hist1_2D.Draw("colz")
canvas.cd(2)
ROOT.gPad.SetRightMargin(0.2)
hist2_2D.Draw("colz")
canvas.cd(2).SetLogz(1)
canvas.cd(3)
ROOT.gPad.SetRightMargin(0.2)
hist3_2D.Draw("colz")

canvas.Print(boson + "_boson_jets_fuehrende_Ordnung_pt_2D_ana.png")
#canvas.Print(boson + "_boson_jets_fuehrende_Ordnung_pt_2D.pdf")
canvas.Clear()
legend.Clear()
###############################################
legend.AddEntry(hist4_2D, "LO", "f")
legend.AddEntry(hist5_2D, "NLO", "f")

canvas.Divide(1,3)
canvas.cd(1).SetLogz(1)
canvas.cd(1)
ROOT.gPad.SetRightMargin(0.2)
hist4_2D.Draw("colz")
canvas.cd(2)
ROOT.gPad.SetRightMargin(0.2)
hist5_2D.Draw("colz")
canvas.cd(2).SetLogz(1)
canvas.cd(3)
ROOT.gPad.SetRightMargin(0.2)
hist6_2D.Draw("colz")

canvas.Print(boson + "_boson_pt_DeltaPhi_2D_ana.png")
#canvas.Print(boson + "_boson_pt_DeltaPhi_2D.pdf")
canvas.Clear()
legend.Clear()
############################################
legend.AddEntry(hist7_2D, "LO", "f")
legend.AddEntry(hist8_2D, "NLO", "f")

canvas.Divide(1,3)
canvas.cd(1).SetLogz(1)
canvas.cd(1)
ROOT.gPad.SetRightMargin(0.2)
hist7_2D.Draw("colz")
canvas.cd(2)
ROOT.gPad.SetRightMargin(0.2)
hist8_2D.Draw("colz")
canvas.cd(2).SetLogz(1)
canvas.cd(3)
ROOT.gPad.SetRightMargin(0.2)
hist9_2D.Draw("colz")

canvas.Print(boson + "_jets_fuehrende_Ordnung_pt_DeltaPhi_2D_ana.png")
#canvas.Print(boson + "_jets_fuehrende_Ordnung_pt_DeltaPhi_2D.pdf")
canvas.Clear()
legend.Clear()
############################################
legend.AddEntry(hist10_2D, "LO", "f")
legend.AddEntry(hist11_2D, "NLO", "f")

canvas.Divide(1,3)
canvas.cd(1).SetLogz(1)
canvas.cd(1)
ROOT.gPad.SetRightMargin(0.2)
hist10_2D.Draw("colz")
canvas.cd(2)
ROOT.gPad.SetRightMargin(0.2)
hist11_2D.Draw("colz")
canvas.cd(2).SetLogz(1)
canvas.cd(3)
ROOT.gPad.SetRightMargin(0.2)
hist12_2D.Draw("colz")

canvas.Print(boson + "_jets_anzahl_HT_2D_ana.png")
#canvas.Print(boson + "_jets_anzahl_HT_2D.pdf")
canvas.Clear()
legend.Clear()
##########################################
legend.AddEntry(hist13_2D, "LO", "f")
legend.AddEntry(hist14_2D, "NLO", "f")

canvas.Divide(1,3)
canvas.cd(1).SetLogz(1)
canvas.cd(1)
ROOT.gPad.SetRightMargin(0.2)
hist13_2D.Draw("colz")
canvas.cd(2)
ROOT.gPad.SetRightMargin(0.2)
hist14_2D.Draw("colz")
canvas.cd(2).SetLogz(1)
canvas.cd(3)
ROOT.gPad.SetRightMargin(0.2)
hist15_2D.Draw("colz")

canvas.Print(boson + "_boson_transverse_mass_pt_2D_ana.png")
#canvas.Print(boson + "_boson_transverse_mass_pt_2D.pdf")
canvas.Clear()
legend.Clear()
###########################################
legend.AddEntry(hist16_2D, "LO", "l")
legend.AddEntry(hist17_2D, "NLO", "l")

canvas.Divide(1,3)
canvas.cd(1).SetLogz(1)
canvas.cd(1)
ROOT.gPad.SetRightMargin(0.2)
hist16_2D.Draw("colz")
canvas.cd(2)
ROOT.gPad.SetRightMargin(0.2)
hist17_2D.Draw("colz")
canvas.cd(2).SetLogz(1)
canvas.cd(3)
ROOT.gPad.SetRightMargin(0.2)
hist18_2D.Draw("colz")

canvas.Print(boson + "_boson_transverse_mass_phizwlundnu_2D_ana.png")
#canvas.Print(boson + "_boson_transverse_mass_phizwlundnu_2D.pdf")
canvas.Clear()
legend.Clear()
###########################################
legend.AddEntry(hist1_3D, "LO", "f")
legend.AddEntry(hist2_3D, "NLO", "f")

canvas_3D.Divide(2,2)
#canvas.cd(1).SetLogy(1)
#canvas.cd(1).SetLogx(1)
canvas_3D.cd(1)
hist1_3D.Draw("BOX2Z")
canvas_3D.cd(2)
hist2_3D.Draw("BOX2Z")
#legend.Draw("same")
#canvas.cd(2).SetLogx(1)
canvas_3D.cd(3)
hist3_3D.Draw("BOX2Z")

canvas_3D.Print(boson + "_boson_pt_jets_fuehrende_Ordnung_pt_DeltaPhi_3D_ana.png")
#canvas.Print(boson + "_boson_pt_jets_fuehrende_Ordnung_pt_DeltaPhi_3D.pdf")
canvas_3D.Clear()
legend.Clear()
##########################################
legend.AddEntry(hist4_3D, "LO", "f")
legend.AddEntry(hist5_3D, "NLO", "f")

canvas_3D.Divide(2,2)
#canvas.cd(1).SetLogx(1)
#canvas.cd(1).SetLogy(1)
canvas_3D.cd(1)
hist4_3D.Draw("box2z")
canvas_3D.cd(2)
hist5_3D.Draw("box2z")
#legend.Draw("same")
#canvas.cd(2).SetLogx(1)
canvas_3D.cd(3)
hist6_3D.Draw("box2z")

canvas_3D.Print(boson + "_boson_pt_jets_fuehrende_Ordnung_pt_anzahl_3D_ana.png")
#canvas.Print(boson + "_boson_pt_jets_fuehrende_Ordnung_pt_anzahl_3D.pdf")
canvas_3D.Clear()
legend.Clear()
############################################
legend.AddEntry(hist7_3D, "LO", "f")
legend.AddEntry(hist8_3D, "NLO", "f")


canvas_3D.Divide(2,2)
#canvas_3D.cd(1).SetLogx(1)
#canvas_3D.cd(1).SetLogy(1)
canvas_3D.cd(1)
hist7_3D.Draw("box2z")
canvas_3D.cd(2)
hist8_3D.Draw("box2z")
#legend.Draw("same")
#canvas.cd(2).SetLogx(1)
canvas_3D.cd(3)
hist9_3D.Draw("box2z")

canvas_3D.Print(boson + "_boson_pt_DeltaPhi_anzahl_3D_ana.png")
#canvas.Print(boson + "_boson_pt_DeltaPhi_anzahl_3D.pdf")
canvas_3D.Clear()
legend.Clear()
################################################


print("finished")
